apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-bot-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: movie-bot-frontend
  template:
    metadata:
      labels:
        app: movie-bot-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: 3000
