apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-bot-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: movie-bot-backend
  template:
    metadata:
      labels:
        app: movie-bot-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
