apiVersion: v1
kind: Service
metadata:
  name: movie-bot-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: movie-bot-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 5000
