apiVersion: v1
kind: Service
metadata:
  name: movie-bot-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: movie-bot-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
