backend:
  image:
    repository: 163880612827.dkr.ecr.us-east-1.amazonaws.com/movie-bot-backend
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5000
frontend:
  image:
    repository: 163880612827.dkr.ecr.us-east-1.amazonaws.com/movie-bot-frontend
    tag: latest
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
