name: "Caller deploy app"

on:
  workflow_dispatch:

jobs:
  Build-Infra:
    # Run the Infra Workflow
    uses: yossisp1972/movie-bot/.github/workflows/deploy.yml@master
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}