name: "Image Workflow"
on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: create ecr repo
        shell: bash
        run: |
          repo=$(aws ecr describe-repositories --repository-names movie-bot-backend || echo "not found")
          if [ -z "$repo" ]; then
            aws ecr create-repository --repository-name movie-bot-backend --region us-east-1
          fi
          repo=$(aws ecr describe-repositories --repository-names movie-bot-frontend || echo "not found")
          if [ -z "$repo" ]; then
            aws ecr create-repository --repository-name movie-bot-frontend --region us-east-1
          fi

      - name: Authenticate docker to ecr
        shell: bash
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 163880612827.dkr.ecr.us-east-1.amazonaws.com

      - name: Build backend image
        run: docker build -t movie-bot-backend:latest .
            docker tag movie-bot-backend:latest 163880612827.dkr.ecr.us-east-1.amazonaws.com/movie-bot-backend:latest
        working-directory: ./backend
      - name: Build frontend image
        run: docker build -t movie-bot-frontend:latest .
             docker tag movie-bot-frontend:latest 163880612827.dkr.ecr.us-east-1.amazonaws.com/movie-bot-frontend:latest
        working-directory: ./frontend
      - name: Push backend image to ECR
        run: docker push 163880612827.dkr.ecr.us-east-1.amazonaws.com/movie-bot-backend:latest
      - name: Push frontend image to ECR
        run: docker push 163880612827.dkr.ecr.us-east-1.amazonaws.com/movie-bot-frontend:latest

